apiVersion: v1
kind: Namespace
metadata:
  name: hello-java
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java
  namespace: hello-java
  labels:
    keel.sh/policy: all
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-java
  template:
    metadata:
      labels:
        app: hello-java
        aadpodidbinding: aad-label
    spec:
      containers:
      - name: hello-java
        image: quay.io/vguar/hello-world-java:v1
        resources:
          requests:
            memory: "1G"
            cpu: "100m"
        # securityContext:
        #   allowPrivilegeEscalation: true
        env:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /cache
            name: cache-volume
      volumes:
        - name: cache-volume
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-java-svc
  namespace: hello-java
  labels:
    environment: dev
spec:
  ports:
    - port: 80
      targetPort: 8080
      name: hello-java
  selector:
    app: hello-java
